apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: mooncard
  labels:
    name: mooncard
    app: mooncard
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mooncard
      app: mooncard
  template:
    metadata:
      labels:
        name: mooncard
        app: mooncard
    spec:
      containers:
      - name: simple-sleeping-pod
        image: public.ecr.aws/nginx/nginx:stable-perl
        envFrom:
        - configMapRef:
            name: simple-configmap
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
