apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-1
  namespace: mooncard
  labels:
    name: mooncard
    app: mooncard
spec:
  containers:
  - name: simple-sleeping-pod
    image: public.ecr.aws/ubuntu/ubuntu:latest
    command: ["sleep", "3600"]
