apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: mooncard
  labels:
    name: mooncard
    app: mooncard
spec:
  selector:
    app: mooncard
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
